// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Exec(arg1, arg2) {
  return window['go']['main']['App']['Exec'](arg1, arg2);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function Parse(arg1) {
  return window['go']['main']['App']['Parse'](arg1);
}
