// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Exec(arg1:string,arg2:boolean):Promise<main.ExecResult>;

export function GetState():Promise<main.State>;

export function Parse(arg1:string):Promise<main.ParseResult>;
