name: Build

on:
  push:
    tags:
      - "*.*.*"
    branches:
      - "main"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.0"

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest

          sudo apt-get update
          sudo apt-get install -y \
            jq \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            nsis \
            # End of package list

          wails doctor

      - name: Prepare things
        id: prepare
        run: |
          mkdir artifacts

          # Extract version from tag
          VERSION=$(git tag --points-at HEAD | head -n1)
          if [[ "$VERSION" != "" ]]; then
            jq '.info.productVersion = "'${VERSION}'"' < wails.json > wails.json.new
            mv wails.json.new wails.json

            echo "Release $VERSION of ${{ github.sha }}" > RELEASE.txt
            echo >> RELEASE.txt
          fi

          cd frontend
          pnpm install
          cd -

      - name: Build for Linux amd64
        run: |
          wails build --platform linux/amd64
          cp -a build/bin/zappac-gui artifacts/zappac-gui-linux-amd64

      # TODO: Crashes with some assembler no such instruction bla bla - maybe needs ARM runner?
      #      - name: Build for Linux arm64
      #        run: |
      #          wails build --platform linux/arm64
      #          cp -a build/bin/zappac-gui artifacts/zappac-gui-linux-arm64

      - name: Build for Windows amd64
        run: |
          wails build --platform windows/amd64
          cp -a build/bin/zappac-gui.exe artifacts/zappac-gui-windows-amd64.exe

      - name: Installer for Windows amd64
        run: |
          wails build --platform windows/amd64 --nsis
          cp -a build/bin/zappac-gui-amd64-installer.exe artifacts/zappac-gui-amd64-installer.exe

      - name: Build for Windows arm64
        run: |
          wails build --platform windows/arm64
          cp -a build/bin/zappac-gui.exe artifacts/zappac-gui-windows-arm64.exe

      - name: Installer for Windows arm64
        run: |
          wails build --platform windows/arm64 --nsis
          cp -a build/bin/zappac-gui-arm64-installer.exe artifacts/zappac-gui-arm64-installer.exe

      # TODO: macOS build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            artifacts

      # Release tagged pushes
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: RELEASE.txt
          files: artifacts/*
